version: "3.2"

services:
  db:
    image: postgres
    container_name: "pg-fiap"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fiap_dev
    ports:
      - 5432:5432

